#CALCULA EL MAYOR DE DOS NUMEROS INGRESADOS

# n1=int(input("INGRESE CUALQUIER NUMERO ENTERO: "))
# n2=int(input("INGRESE OTRO NUMERO ENTERO: "))

# if n1>n2 :
#     print("SU NUMERO ES MAYOR")
# else:
#     print("SU NUMERO ES MENOR")


#---------- TALLER CONDICIONALES Y OPERACIONES MATEMATICAS ------------
#  1

# n1=int(input("INGRESE UN NUMERO ENTERO: "))

# if n1<0 :
#     print(F"SU NUMERO ES NEGATIVO PORQUE ES: {n1}")
# elif n1>0 :
#     print(F"SU NUMERO ES POSITVO PORQUE ES: {n1}")   
# else :
#     print(F"SU NUMERO ES CERO")

#  2

# n1=int(input("INGRESE CUALQUIER NUMERO ENTERO: "))
# n2=int(input("INGRESE OTRO NUMERO ENTERO: "))

# if n1>n2:
#     print(F"SU NUMERO : {n1} ES MAYOR A : {n2}")
# else :
#     print(F"SU NUMERO : {n1} ES MENOR A: {n2}")
# if n2>n1:
#     print(F"SU NUMERO : {n2} ES MAYOR A : {n1}")
# else:
#     print(F"SU NUMERO : {n2} ES MENOR A: {n1}")

#  3

# p1=int(input("INGRESE UN NUMERO ENTERO: "))

# if p1 % 2 == 0:
#     print("SU NUMERO ES PAR")
# else:
#     print("SU NUMERO ES IMPAR")

#  4

# nm1=int(input("INGRESE UN NUMERO ENTERO: "))
# if nm1 >= 10 and nm1 <= 20: 
#     print("SU NUMERO ESTA ENTRE 10 - 20")
# else:
#     print("SU NUMERO NO ESTA ENTRE 10 - 20")

#  5

# nu1=int(input("INGRESE EL 1 NUMERO ENTERO: "))
# nu2=int(input("INGRESE EL 2 NUMERO ENTERO: "))
# nu3=int(input("INGRESE EL 3 NUMERO ENTERO: "))

# if nu1 > nu2 and nu3:
#     print(f"EL NUMERO: {nu1} ES MAYOR A TODOS")
# if nu2 > nu3 and nu1:
#     print(f"EL NUMERO: {nu2} ES MAYOR A TODOS")
# if nu3 > nu2 and nu1:
#     print(f"EL NUMERO: {nu3} ES MAYOR A TODOS")

#  6

# pr1=float(input("INGRESE UN PRECIO: "))

# if pr1 > 100 :
#     U= 10/100 * pr1
#     p= pr1 - U
#     print(F"COMO EL PRECIO PASO A 100$ SE LE APLICA EL DESCUENTO DE 10% : {p}")
# else:
#     print(F"A SU PRECIO NO SE LE APLICA DESCUENTO: {pr1}")

#  7

# ed=int(input("INGRESE SU EDAD: "))
# if ed >= 18:
#     print(F"SU EDAD ES : {ed} ENTONCES PUEDES VOTAR")
# else:
#     print(F"SU EDAD ES : {ed} ENTONCES NO PUEDES VOTAR")    

#  8

# pr2=float(input("INGRESE SU PRECIO: "))
# vp=input("ERES CLIENTE VIP O NORMAL: ")

# if vp == "VIP":
#     D=20/100*pr2
#     P=pr2+D
#     print(f"COMO ERES CLIENTE VIP SE TE APLICA EL DESCUENTO DE 20%: {P}")
# else:
#     print(f"COMO NO ERES CLIENTE VIP TU PRECIO SIGUE SIENDO: {pr2}")

#  9

# nm1=int(input("INGRESA UN NUMERO ENTERO: "))
# if nm1 % 5 == 0 and nm1 % 3 == 0 :
#     print(f"SU NUMERO: {nm1} ES MULTIPLO DE 3 Y 5")
# else:
#     print("SU NUMERO NO ES MULTIPLO DE 3 Y 5")

#  10













